/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class SyncCache {
  constructor(capacity: number)
  set(key: string, value: string): void
  mset(items: Array<[string, string]>): void
  get(key: string): string | null
}
